### PR TITLE
Add Docker deployment configuration

### PR DESCRIPTION
**Pull request by LarsSelbekk**

### CODE REVIEW

**Comment by mathiazom** [comment]
Is this just me? (for `lab-assistant_dev`)

```
Error from chokidar (/app/node_modules/@ant-design/icons/es/icons): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/@ant-design/icons/es/icons'
Error from chokidar (/app/node_modules/@babel/runtime/helpers/esm): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/@babel/runtime/helpers/esm'
Error from chokidar (/app/node_modules/@pmmmwh/react-refresh-webpack-plugin/client): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/@pmmmwh/react-refresh-webpack-plugin/client'
Error from chokidar (/app/node_modules/antd/dist): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/antd/dist'
Error from chokidar (/app/node_modules/antd/es/alert): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/antd/es/alert'
Error from chokidar (/app/node_modules/antd/es/back-top): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/antd/es/back-top'
Error from chokidar (/app/node_modules/antd/es/calendar): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/antd/es/calendar'
Error from chokidar (/app/node_modules/antd/es/cascader): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/antd/es/cascader'
Error from chokidar (/app/node_modules/antd/es/comment): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/antd/es/comment'
Error from chokidar (/app/node_modules/antd/es/date-picker/locale): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/antd/es/date-picker/locale'
Error from chokidar (/app/node_modules/antd/es/dropdown): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/antd/es/dropdown'
Error from chokidar (/app/node_modules/antd/es/grid): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/antd/es/grid'
Error from chokidar (/app/node_modules/antd/es/input-number): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/antd/es/input-number'
Error from chokidar (/app/node_modules/antd/es/locale-provider): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/antd/es/locale-provider'
Error from chokidar (/app/node_modules/antd/es/message/hooks): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/antd/es/message/hooks'
Error from chokidar (/app/node_modules/antd/es/notification/hooks): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/antd/es/notification/hooks'
Error from chokidar (/app/node_modules/antd/es/popconfirm): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/antd/es/popconfirm'
Error from chokidar (/app/node_modules/antd/es/rate): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/antd/es/rate'
Error from chokidar (/app/node_modules/antd/es/select/utils): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/antd/es/select/utils'
Error from chokidar (/app/node_modules/antd/es/spin): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/antd/es/spin'
Error from chokidar (/app/node_modules/antd/es/table): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/antd/es/table'
Error from chokidar (/app/node_modules/antd/es/tag): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/antd/es/tag'
Error from chokidar (/app/node_modules/antd/es/tooltip): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/antd/es/tooltip'
Error from chokidar (/app/node_modules/antd/es/tree/utils): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/antd/es/tree/utils'
Error from chokidar (/app/node_modules/antd/es/version): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/antd/es/version'
Error from chokidar (/app/node_modules/axios/lib/adapters): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/axios/lib/adapters'
Error from chokidar (/app/node_modules/axios/lib/helpers): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/axios/lib/helpers'
Error from chokidar (/app/node_modules/classnames): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/classnames'
Error from chokidar (/app/node_modules/dom-align/dist-web): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/dom-align/dist-web'
Error from chokidar (/app/node_modules/moment): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/moment'
Error from chokidar (/app/node_modules/querystring-es3): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/querystring-es3'
Error from chokidar (/app/node_modules/rc-checkbox/es): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/rc-checkbox/es'
Error from chokidar (/app/node_modules/rc-dialog/es): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/rc-dialog/es'
Error from chokidar (/app/node_modules/rc-field-form/es/utils): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/rc-field-form/es/utils'
Error from chokidar (/app/node_modules/rc-input-number/es/hooks): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/rc-input-number/es/hooks'
Error from chokidar (/app/node_modules/rc-menu/es/SubMenu): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/rc-menu/es/SubMenu'
Error from chokidar (/app/node_modules/rc-motion/es): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/rc-motion/es'
Error from chokidar (/app/node_modules/rc-overflow/es): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/rc-overflow/es'
Error from chokidar (/app/node_modules/rc-picker/es): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/rc-picker/es'
Error from chokidar (/app/node_modules/rc-picker/es/panels/DatePanel): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/rc-picker/es/panels/DatePanel'
Error from chokidar (/app/node_modules/rc-picker/es/panels/MonthPanel): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/rc-picker/es/panels/MonthPanel'
Error from chokidar (/app/node_modules/rc-picker/es/panels/YearPanel): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/rc-picker/es/panels/YearPanel'
Error from chokidar (/app/node_modules/rc-resize-observer/es): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/rc-resize-observer/es'
Error from chokidar (/app/node_modules/rc-select/es/interface): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/rc-select/es/interface'
Error from chokidar (/app/node_modules/rc-steps/es): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/rc-steps/es'
Error from chokidar (/app/node_modules/rc-table/es): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/rc-table/es'
Error from chokidar (/app/node_modules/rc-table/es/Panel): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/rc-table/es/Panel'
Error from chokidar (/app/node_modules/rc-table/es/utils): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/rc-table/es/utils'
Error from chokidar (/app/node_modules/rc-tabs/es/hooks): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/rc-tabs/es/hooks'
Error from chokidar (/app/node_modules/rc-tree-select/es/hooks): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/rc-tree-select/es/hooks'
Error from chokidar (/app/node_modules/rc-trigger/es/Popup): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/rc-trigger/es/Popup'
Error from chokidar (/app/node_modules/rc-util/es/Children): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/rc-util/es/Children'
Error from chokidar (/app/node_modules/rc-util/es/utils): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/rc-util/es/utils'
Error from chokidar (/app/node_modules/rc-virtual-list/es/hooks): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/rc-virtual-list/es/hooks'
Error from chokidar (/app/node_modules/react-dev-utils/node_modules/strip-ansi): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/react-dev-utils/node_modules/strip-ansi'
Error from chokidar (/app/node_modules/react-refresh/cjs): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/react-refresh/cjs'
Error from chokidar (/app/node_modules/regenerator-runtime): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/regenerator-runtime'
Error from chokidar (/app/node_modules/scroll-into-view-if-needed/es): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/scroll-into-view-if-needed/es'
Error from chokidar (/app/node_modules/toggle-selection): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/toggle-selection'
Error from chokidar (/app/node_modules/webpack/buildin): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/webpack/buildin'
Error from chokidar (/app/src): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src'
Error from chokidar (/app/src/api): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/api'
Error from chokidar (/app/src/components/AuthForm): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/AuthForm'
Error from chokidar (/app/src/components/AwardsTab): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/AwardsTab'
Error from chokidar (/app/src/components/CommitList): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/CommitList'
Error from chokidar (/app/src/components/CommitsTab): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/CommitsTab'
Error from chokidar (/app/src/components/Header): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/Header'
Error from chokidar (/app/src/components/Info): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/Info'
Error from chokidar (/app/src/components/IssueList): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/IssueList'
Error from chokidar (/app/src/components/IssuesTab): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/IssuesTab'
Error from chokidar (/app/src/components/Page): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/Page'
Error from chokidar (/app/src/components/Tab): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/Tab'
Error from chokidar (/app/src/webstorage): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/webstorage'
Error from chokidar (/app/src): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/App.css'
Error from chokidar (/app/src): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/App.test.tsx'
Error from chokidar (/app/src): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/App.tsx'
Error from chokidar (/app/src): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/gitlab-logo-w.png'
Error from chokidar (/app/src): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/gitlab-logo.png'
Error from chokidar (/app/src): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/index.css'
Error from chokidar (/app/src): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/index.tsx'
Error from chokidar (/app/src): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/react-app-env.d.ts'
Error from chokidar (/app/src): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/reportWebVitals.ts'
Error from chokidar (/app/src): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/setupTests.ts'
Error from chokidar (/app/src/api): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/api/ApiBase.ts'
Error from chokidar (/app/src/api): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/api/Awards.ts'
Error from chokidar (/app/src/api): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/api/Commits.ts'
Error from chokidar (/app/src/api): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/api/Issues.ts'
Error from chokidar (/app/src/api): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/api/MergeRequest.ts'
Error from chokidar (/app/src/api): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/api/Notes.ts'
Error from chokidar (/app/src/api): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/api/Users.ts'
Error from chokidar (/app/src/components/AuthForm): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/AuthForm/index.tsx'
Error from chokidar (/app/src/components/AuthForm): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/AuthForm/styles.css'
Error from chokidar (/app/src/components/AwardsTab): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/AwardsTab/index.tsx'
Error from chokidar (/app/src/components/AwardsTab): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/AwardsTab/styles.css'
Error from chokidar (/app/src/components/CommitList): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/CommitList/index.tsx'
Error from chokidar (/app/src/components/CommitList): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/CommitList/styles.css'
Error from chokidar (/app/src/components/CommitsTab): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/CommitsTab/index.tsx'
Error from chokidar (/app/src/components/CommitsTab): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/CommitsTab/util.ts'
Error from chokidar (/app/src/components/Header): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/Header/index.tsx'
Error from chokidar (/app/src/components/Header): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/Header/styles.css'
Error from chokidar (/app/src/components/Info): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/Info/index.tsx'
Error from chokidar (/app/src/components/Info): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/Info/styles.css'
Error from chokidar (/app/src/components/IssueList): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/IssueList/index.tsx'
Error from chokidar (/app/src/components/IssuesTab): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/IssuesTab/index.tsx'
Error from chokidar (/app/src/components/IssuesTab): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/IssuesTab/styles.css'
Error from chokidar (/app/src/components/IssuesTab): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/IssuesTab/utlis.ts'
Error from chokidar (/app/src/components/Page): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/Page/index.tsx'
Error from chokidar (/app/src/components/Page): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/Page/styles.css'
Error from chokidar (/app/src/components/Tab): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/Tab/index.tsx'
Error from chokidar (/app/src/components/Tab): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/components/Tab/styles.css'
Error from chokidar (/app/src/webstorage): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/webstorage/WebStorage.ts'
```

**Comment by LarsSelbekk** [comment]
Might not have checked the dev log, will investigate

**Comment by LarsSelbekk** [comment]
@mathiazom when you fixed it by increasing the limit, did you do it on your own operating system or in Docker?

**Comment by mathiazom** [comment]
> @mathiazom when you fixed it by increasing the limit, did you do it on your own operating system or in Docker?

I was not able to change the limit, and only tried inside the container.

**Comment by LarsSelbekk** [comment]
According to [this](https://stackoverflow.com/a/60451758/15455509), the limit needs to be increased on the host system, which on Docker for Mac is a Linux VM. The command should be `docker run --rm --privileged alpine sysctl -w fs.inotify.max_user_watches=1048576` for a limit of 1048576. The set limit should apply to all (new?) containers until restart. To make it permanent, use `docker run --rm --privileged alpine echo fs.inotify.max_user_watches=1048576 | tee -a /etc/sysctl.conf && sysctl -p`. The limit can be checked on any system using `cat /proc/sys/fs/inotify/max_user_watches` I think.

**Comment by LarsSelbekk** [comment]
Try [this](https://stackoverflow.com/a/55543310) for Debian (it's the same as the permanent solution, without Docker). Might need to use `--system` instead of `-p` per top comment on the linked answer.

**Comment by mathiazom** [comment]
> Try [this](https://stackoverflow.com/a/55543310) for Debian (it's the same as the permanent solution, without Docker). Might need to use `--system` instead of `-p` per top comment on the linked answer.

According to a method from the comments my server had the value set to a whopping **4** :thinking:  While my desktop was cruising on 7804. A value of 78040 seems to do the trick at least, let's hope it doesn't burn down the house :crossed_fingers:

**Review by mathiazom — APPROVED** [review]

**Comment by LarsSelbekk** [comment]
Sorry for the force-push (rebase + a few README additions + project rename in package.json). I just learned of `git range-diff origin/master..origin/i6/docker-deployment-setup v1.0-anonymified..i6/docker-deployment-setup`, which shows the diff of diffs/commits between two commit ranges.

**Pull request merged**
